version: "3.8"

services:
  stock-pipeline:
    build: .
    container_name: miami-stock-pipeline
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped